"""Add Scheme, Channel Partner etc Models

Revision ID: 68c4ad53ae05
Revises: c5fbd1ac0730
Create Date: 2026-09-05 14:50:17.752075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c4ad53ae05'
down_revision: Union[str, Sequence[str], None] = 'c5fbd1ac0730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
